# Generated by Django 4.1 on 2022-08-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_category_alter_expense_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('0', 'Other'), ('1', 'Food'), ('2', 'Health'), ('3', 'Dwelling'), ('4', 'Transportation'), ('5', 'Education'), ('6', 'Enterprise'), ('7', 'Unexpected')], default=0, max_length=1),
        ),
    ]
