# Generated by Django 4.1 on 2022-08-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_expense_category_alter_expense_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Other', 'Other'), ('Food', 'Food'), ('Health', 'Health'), ('Dwelling', 'Dwelling'), ('Transportation', 'Transportation'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Unexpected', 'Unexpected')], default='Other', max_length=128),
        ),
    ]
